name: dainik_ujala_admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  http: ^0.13.5
  flutter_widget_from_html: ^0.9.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
