// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqx_DNxZ7_fCdVbsxcOU_sglWfqDSlhoM',
    appId: '1:8188421520:web:3b20fd1a564d64fc79ff15',
    messagingSenderId: '8188421520',
    projectId: 'dainik-ujala-live',
    authDomain: 'dainik-ujala-live.firebaseapp.com',
    storageBucket: 'dainik-ujala-live.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC9zwqNU3YyR0exxtIIKg0Spr5EncKmW4',
    appId: '1:8188421520:android:154a0a22349c5c0379ff15',
    messagingSenderId: '8188421520',
    projectId: 'dainik-ujala-live',
    storageBucket: 'dainik-ujala-live.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdFyVDCS-4AAIB4wRseCuIKHFCOPo9MsM',
    appId: '1:8188421520:ios:d8a96ad3b506e6bb79ff15',
    messagingSenderId: '8188421520',
    projectId: 'dainik-ujala-live',
    storageBucket: 'dainik-ujala-live.appspot.com',
    iosClientId: '8188421520-rdke50tt0upir4qb0f98q0hmg84vij96.apps.googleusercontent.com',
    iosBundleId: 'com.example.dainikUjalaAdmin',
  );
}
